### ISSUE TITLE
KeyError when using snpEff-annotated VCF with NextProt or Motif annotations

### ISSUE THREAD

**Issue by bpow** [brentp/geneimpacts#3] opened 2015-10-28 13:13 UTC
The default annotations provided by snpEff include NextProt and Motif consequences. `geneimpacts` exits with a KeyError (in `geneimpacts/effect.py` line 557, for example: `KeyError: 'NEXT_PROT[disulfide_bond]'` when executing the line `sevs = [IMPACT_SEVERITY[csq] for csq in self.consequences]`) when these are present, since there is no entry in `self.consequences` for these effects.

**Comment by brentp** [comment] 2015-10-28 13:43
Thanks for reporting and finding the cause.
I'll update the gene impacts module can you send a vcf that recreates this problem?

**Comment by bpow** [comment] 2015-10-28 20:19
Sure, here is a [gist](https://gist.github.com/bpow/e4da0d25d6c01762274f) with a vcf file that demonstrates the error.

**Comment by bpow** [comment] 2015-10-29 15:46
This may only be an issue when the snpEff '-classic' and '-formatEff' options are used, not with the newer ANN format.

**Comment by brentp** [comment] 2015-10-29 19:29
this is fixed in c952623

**Closed** 2015-10-29 19:32 UTC
